[tool.pytest.ini_options]
addopts = "--cov=app --cov-report=html"
testpaths = ["tests"]
console_output_style = "progress"
log_auto_indent = true
log_cli = true
log_cli_level = "ERROR"
required_plugins = "pytest-cov>=4.1.0 pytest-xdist>=3.5.0"